### ISSUE TITLE
Инцидент

### ISSUE THREAD

**Issue by tishkovets** [NodaSoft/hr#392]
Потратил несколько часов на решение тестового задания https://github.com/NodaSoft/hr/tree/main/php/v2
Задание хитрое, было даже интересно разделить интерфейсы. По этой части респект тем, кто его запостил.

Далее откликнулся на вакансию на hh, указал ссылку на свою репу. Через несколько дней в телегу постучала hr c предложением провести мит. Окей, назначали время и созвонились. 

Честно говоря, за все время первый раз столкнулся с таким способом взаимодействия с hr. Обычно всегда попадал на положительно-нейтральное общение на этом этапе. Здесь же две звезды снизошли до разговора и соблаговолили со мной пообщаться) Дали понять, что мне несказанно повезло, что они мне нписали после тестового задания) Ну ок, подумал я и стал ждать обратной связи через несколько дней.

Через несколько дней обнаружил, что диалог с  HR просто удален. Ну я понимаю, если бы у нас не было стадии тестового задания, ну а так это просто супер свинство. Мой код был не настолько плох, и я в этом уверен. Никто никому ничем не обязан, это понятно. Но ориентированность на людей просто впечатляет) Интересно у них в команде тоже общение на таком уровне происходит? Впрочем, не имеет значения)

Так что такой опыт есть, может кому-то пригодится.

**Comment by dev-nodasoft** [comment]
Максим, добрый день! Благодарим вас за полезный для нас отзыв. С его помощью мы обратили внимание на эту ситуацию, разобрались и нашли места, где можем улучшить процесс найма специалистов. Ваш отзыв мы даже опубликовали во внутреннем новостном канале для наших сотрудников в качестве примера позитивного влияния на улучшение процессов в компании. Обратная связь — это огромная польза для компании и шанс стать лучше.

Справедливости ради для читателей отметим, что изложенная вами история не совсем сходится с нашей версией. Мы её изложим для полноты картины:
как вы и написали, в среду у вас было собеседование с hr-специалистами, на котором вам сказали, что ответ дадут в пятницу. В пятницу у сотрудника стояла задача на вторую половину дня написать вам, но вы опередили и написали первым, вам ответили, что решение принято и вы нам не подходите, в ответ вы поставили реакцию на сообщение, после чего сотрудник удалила чат.

Теперь мы хотим исправить свинство, о которым вы говорите, и дать развернутую обратную связь:
ваш код действительно был неплох и мы в этом убедились до того, как позвать вас на собеседование. Оценку результата теста делал тот сотрудник, который сам это задание и написал. Результат теста его устроил, поэтому вас пригласили на собеседование — это и есть первый этап отбора кандидата. Следующим этапом проводится собеседование hr-специалистами, их задача — максимально ответственно разобраться подходит ли кандидат в нашу команду, будет ли нам и ему комфортно работать друг с другом. Если ответ положительный, то заключительным этапом проводится собеседование с техническими специалистами. В вашем случае получилось, что тестовое задание нам понравилось, но возникли сомнения, что вы подходите в нашу команду. В первую очередь мы работаем с людьми, а не с кодом, поэтому для нас важно быть, так сказать, на одной волне.

Надеемся, на этот раз нам удалось донести вам нашу позицию. Сожалеем, что не сделали это сразу. Ещё раз благодарим вас за отзыв и желаем успехов в поиске работы!

**Comment by tishkovets** [comment]
Приветствую, [dev-nodasoft](https://github.com/dev-nodasoft)

Удивительно, конечно, что мы с вами не можем быть на одной волне... Обычно, слышу от HR и просто разных людей инфу о том, что взаимодействие с людьми, уменее слушать и слышать, софтскиллз, это - моя сильная сторона. Допускаю, конечно, что я могу и не подходить под ваши критерии.

Тем не менее, если для читателей мы говорим о какой-то справедливости, то озвученная Вами информация немного не соответствует действительности.  Мне, действительно, сказали, что обратная связь будет в пятницу. И вот под конец рабочего дня я и увидел удаленную переписку. Никаких откликов на hh в этот момент еще не было, как и самой переписки. То есть она была просто удалена. И это вызвало мое возмущение, так как я потратил свое время за решением задачи. И если вы говорите, что в первую очередь работаете с людьми, то в этом месте я этого совсем не почувствовал. 

Я запомнил контакт HR и сам у нее спросил про обратную связь. В этот момент я и получил сообщение о том, что, мол, пятница еще не закончилась со смайликами) И отказ. После этого я сам удалил эту переписку. Вот так это было.  И совершенно не известно, была бы вообще какаято обратная связь, если бы я не написал. 

И теперь хотелось бы еще написать про сам первичный мит. Вероятно сотрудники HR великие знатоки человечских душ, так как за те 12 минут интервью, что у нас было, они совершенно точно поняли, что нам не по пути. Чтож, такое вполне может быть. Однако, ей Богу, сколько общаюсь с HR ни разу не видел более незаинтересованных в общении чем эти. При этом, как я и написал ранее, атмосфера на мите совершенно не располагала к диалогу. От слова совсем. Вещь субъективная, но я настаиваю)

Полагаю, что у вас отличная компания и вызывает сожаление тот факт, что так получилось
Благодарю за ответ и обратную связь.  

С уважением

**Comment by dev-nodasoft** [comment]
Максим, благодарим за дополнительные подробности!
