### ISSUE TITLE
Выполнил тестовое задание - нулевая обратная связь, шаблонный отказ

### ISSUE THREAD

**Issue by Rustammus** [NodaSoft/hr#407]
Отвратное отношение к кандидатам, потратил несколько часов на задание, старался сделать как лучше.
Итог - шаблонный отказ в hh, ни слова про тестовое, впустую потраченное время.
Видимо прошлый отзыв правдивый

**Comment by dev-nodasoft** [comment]
Рустам, благодарим вас за отзыв!
Видим, что вы уже ознакомились с нашим ответом на прошлый отзыв. Как видите, мы подтвердили, что ситуация действительно имела место быть.
После предыдущего отзыва мы уже внесли изменения в процесс найма специалистов, чтобы снизить вероятность, что наши действия причинят им дискомфорт. Желаем удачи в поиске работы!
